# Developer workflow — everything runs through Docker. `make help` lists targets.
#
# Usage:
#   make up      — start the dev stack (API + database)
#   make seed    — load the catalogs into the database
#   make test    — run the test suite
#   make down    — stop the stack
#
# The command targets (fetch / seed / test / lint) exec into the running
# api container, so run `make up` first.

DEV := docker compose -f docker-compose.dev.yml
# Run a command inside the running api container (no host toolchain required).
EXEC_API := docker exec payback_api

.DEFAULT_GOAL := help
.PHONY: help up down logs fetch init seed embed eval demo perf test lint build-images \
        check-secrets deploy-aws redeploy-aws seed-aws destroy-aws deploy-gcp seed-gcp destroy-gcp

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

up: ## Build and start the dev stack (API + database)
	$(DEV) up -d --build

down: ## Stop the dev stack and remove volumes
	$(DEV) down -v

logs: ## Tail the API logs
	$(DEV) logs -f api

fetch: ## Refresh the Open Food Facts catalog snapshot (needs network)
	$(EXEC_API) python -m data.fetch_off

init: ## Create the database schema (db/init.sql; idempotent) — the same path dev and cloud use
	$(EXEC_API) python -m data.init_db

seed: init ## Create the schema then load the committed catalog snapshots
	$(EXEC_API) python -m data.seed

embed: ## Compute embeddings for products (run after seed; idempotent)
	$(EXEC_API) python -m data.embed

eval: ## A/B-evaluate the filter × ranker strategies (nDCG/Recall/MRR; run after embed)
	$(EXEC_API) python -m data.eval

demo: ## Run the 5-query demo against the live assistant (needs an LLM key; run after embed)
	$(EXEC_API) python /demo/run_demo.py

perf: ## Load-test the assistant: latency p50/p95/p99 + cost per 1000 (needs an LLM key)
	$(EXEC_API) python /perf/run_perf.py

test: ## Run the test suite
	$(EXEC_API) python -m pytest

lint: ## Lint the codebase
	$(EXEC_API) ruff check .

# ── Pre-push gate (showcase branch) ─────────────────────────────────
# Build BOTH production images the way CI does (api + web). The web image's `npm ci` resolution only
# breaks inside the Docker build (not in a plain `npm run build`), so run this before pushing the
# showcase branch — it's exactly what .github/workflows/ci.yml checks.
build-images: ## Build the prod api + web Docker images locally (catch build breaks before pushing)
	docker build -t payback-api:ci ./apps/backend
	docker build -t payback-web:ci --build-arg NEXT_PUBLIC_API_BASE=https://api.payback.mhannani.me ./apps/frontend

# ── Cloud deployment ────────────────────────────────────────────────
# Each cloud is a self-contained Terraform module under infra/<cloud>/. Fill in
# infra/<cloud>/terraform.tfvars (copy from .example) and export the secrets, then:
#   make deploy-aws → make seed-aws → (hit the URL) → make destroy-aws
# The only secret to provide is the LLM provider key (the DB password is generated by Terraform).
# It comes from the environment, never a committed file:
#   export TF_VAR_llm_api_key=sk-...
TF_AWS := terraform -chdir=infra/aws
TF_GCP := terraform -chdir=infra/gcp

# Deploy an IMMUTABLE image tag by default: the current commit SHA, which CI publishes alongside
# :latest. Pinning the SHA makes every deploy traceable to a commit and rollback-able (just deploy
# a previous SHA), and a new SHA guarantees a new task definition → a guaranteed image roll.
# Override for the quick path: `make redeploy-aws IMAGE_TAG=latest`.
# Full SHA to match the tag CI publishes (`${{ github.sha }}` in .github/workflows/build.yml).
IMAGE_REPO := ghcr.io/mhannani/payback-assistant
IMAGE_TAG  ?= $(shell git rev-parse HEAD)
IMAGE      := $(IMAGE_REPO):$(IMAGE_TAG)

# Fail fast with an actionable message if the LLM key isn't exported (a bare terraform run would
# otherwise print a cryptic "No value for required variable").
check-secrets:
	@test -n "$$TF_VAR_llm_api_key" || { echo "✗ TF_VAR_llm_api_key not set. Run: export TF_VAR_llm_api_key=sk-..."; exit 1; }

deploy-aws: check-secrets ## Provision the AWS stack at the current commit's image (override: IMAGE_TAG=latest)
	$(TF_AWS) init -input=false
	$(TF_AWS) apply -input=false -auto-approve -var 'image=$(IMAGE)'
	@echo "Service: $$($(TF_AWS) output -raw service_url)  (image $(IMAGE_TAG))  —  next: make seed-aws"

redeploy-aws: check-secrets ## Roll the live service to IMAGE_TAG (default: current commit SHA) — no data loss
	$(TF_AWS) apply -input=false -auto-approve -var 'image=$(IMAGE)'
	@echo "Rolled payback-api to image $(IMAGE_TAG)."

seed-aws: ## Run the one-off seed job in-VPC (init_db → seed → embed) against RDS
	@region=$$($(TF_AWS) output -raw region); \
	task=$$(aws ecs run-task \
	  --cluster "$$($(TF_AWS) output -raw cluster)" \
	  --task-definition "$$($(TF_AWS) output -raw seed_task)" \
	  --launch-type FARGATE --region "$$region" \
	  --network-configuration "awsvpcConfiguration={subnets=[$$($(TF_AWS) output -raw subnets_csv)],securityGroups=[$$($(TF_AWS) output -raw service_security_group)],assignPublicIp=ENABLED}" \
	  --query 'tasks[0].taskArn' --output text); \
	echo "Seed job started ($${task##*/}). It loads the catalog + embeddings, then exits (~2 min)."; \
	echo "Watch: aws logs tail /ecs/payback-api --region $$region --follow"

destroy-aws: check-secrets ## Tear down the AWS stack
	$(TF_AWS) destroy -input=false -auto-approve

deploy-gcp: ## Provision the GCP stack at the current commit's image (override: IMAGE_TAG=latest)
	$(TF_GCP) init -input=false
	$(TF_GCP) apply -input=false -auto-approve -var 'image=$(IMAGE)'
	@echo "Service: $$($(TF_GCP) output -raw service_url)  (image $(IMAGE_TAG))  —  next: make seed-gcp"

seed-gcp: ## Run the one-off Cloud Run seed job (init_db → seed → embed) against Cloud SQL
	gcloud run jobs execute $$($(TF_GCP) output -raw seed_job) --region "$$($(TF_GCP) output -raw region)" --wait

destroy-gcp: check-secrets ## Tear down the GCP stack
	$(TF_GCP) destroy -input=false -auto-approve
